### ISSUE TITLE
Support for custom / user-defined endpoint names

### ISSUE THREAD

**Issue by ilazakis** [Kenza-AI/sagify#90] opened 2019-06-16 13:45 UTC
I’d like to be able to define a name for the endpoint when I call ‘deploy’ for easier later processing and testing.

[Docs](https://sagemaker.readthedocs.io/en/stable/model.html)

**Comment by ilazakis** [comment] 2019-06-16 13:47
@pm3310 this is basically the same thing we did in #88

**Comment by pm3310** [comment] 2019-07-07 12:56
Duplicate of https://github.com/Kenza-AI/sagify/issues/91

**Closed by pm3310** 2019-07-07 12:56 UTC
Labels: enhancement
